### ISSUE TITLE
Installation fails on Manjaro 20.1

### ISSUE THREAD

**Issue by Yethal** [RoPieee/roon-on-wine#10]
kernel version: 5.8.1
Wine version: 5.15
Winetricks version: 20200412
After running the script an unhandled exception in wine occurs and Wine window appears with following message: ""The program mscorsvw.exe has encountered a serious issue and needs to close. We are sorry for the inconvenience.". After pressing the close button the exact same exception is logged in the termina land the same window appears again ad infinitum. Full log attached to the ticket.

**Comment by Yethal** [comment]
[roon.log](https://github.com/RoPieee/roon-on-wine/files/5137238/roon.log)

**Comment by ligno** [comment]
I have been using Roon on Wine and Manjaro for almost 2 years. Around the start of 2020 I experienced similar issue after update of Manjaro. Don't know details of the error message anymore. For me the solution was to force Wine to older version (4.2) and since then I don't have any issues. Is kind of workaround, but for me it works fine. I do use Wine only for Roon.

**Comment by Yethal** [comment]
@ligno How did you force an older Wine version? Did you build it from source manually?

**Comment by Yethal** [comment]
For whoever stumbles upon this issue in the future: you need to downgrade Wine to version 5.11. Easiest way to do this on arch based distro is to install downgrade from aut and running 'downgrade wine=5.11'. fterwards the script will work just fine
